authorName: default
experimentName: price_volatility
trialConcurrency: 3
maxExecDuration: 100h
maxTrialNum: 20
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
trial:
  # argv[1]: model, argv[2]: denoising or not, argv[3]: epochs
  # 1: Linear 2: MC dropout 3: Plus Minus
  command: python3 main.py 2 0 1500
  codeDir: .
  gpuNum: 1
localConfig:
  maxTrialNumPerGpu:  2
